### ISSUE TITLE
Setting up Project Environment

### ISSUE THREAD

**Issue by vvs-basanth** [StellaX-Browser/stellax.webpage#12]

**Comment by SRUTHISAMHITA28** [comment]
![Image](https://github.com/user-attachments/assets/c73321e9-fadc-41bd-87c9-d69234909146)
@vvs-basanth  ready for review

**Comment by patnaikakhil** [comment]
![Image](https://github.com/user-attachments/assets/c1c9bc40-78c8-4169-995d-80c0e3080e03)
@vvs-basanth
