### ISSUE TITLE
Low-fidelity Footer

### ISSUE THREAD

**Issue by vvs-basanth** [StellaX-Browser/stellax.webpage#26]
Checkout the final draft page in the figma file and @SRUTHISAMHITA28  you are free to take help of the developer tools in the figma.

@aishuakkilam  talk to your team and finalize the Navbar as soon as you can to complete it and handover the designs to @SRUTHISAMHITA28  .

I am marking this issue as **Inprogress**.

**Comment by SruthiSamhita** [comment]
![Image](https://github.com/user-attachments/assets/06bb23d9-0a4b-4d3b-95f4-4f63a230f297)
@vvs-basanth ready for review
